### ISSUE TITLE
Problems with base64 for data field and getTransactionsFromWalletUrl

### ISSUE THREAD

**Issue by juliancwirko** [ElrondNetwork/elrond-sdk-erdjs-web-wallet-provider#3]
Hey, I try to get a transaction from the URL using `getTransactionsFromWalletUrl(),` which works as expected. It gives me the `PlainSignedTransaction.` Then, I would like to send such transaction using the API provider. Would it be that `getTransactionsFromWalletUrl()` is missing the 'base64' encode functionality for the `data` field? Because I tried many different options, and this is what worked for me: 

```typescript
const txs = webWalletProvider.getTransactionsFromWalletUrl();
const transaction = txs?.[0];
if (transaction) {
  transaction.data = Buffer.from(transaction.data).toString('base64');
  await apiNetworkProvider.sendTransaction(
    Transaction.fromPlainObject(transaction)
  );
}
```

Or maybe there should be an additional method similar to `prepareWalletTransaction` but for the plain object, not Transaction. 

It would be awesome to have an example for the flow like that:
1. Sign using the web wallet provider
2. Get the signed tx data from the URL
3. Prepare it properly 
4. Send the transaction using the API network provider

**Comment by andreibancioiu** [comment]
@juliancwirko, sorry for the delayed response :pray: 

Indeed, currently, a workaround is needed to resolve the impedance between the results from the web wallet provider and erdjs's `Transaction` object.

The workaround is now described here, as well:
https://docs.elrond.com/sdk-and-tools/erdjs/erdjs-signing-providers/#signing-transactions

An example can be found here:
https://github.com/ElrondNetwork/elrond-sdk-erdjs-examples/blob/v0.1.0/signing-providers/src/web-wallet.js

However, a fix will be applied, so that points 1-4 would not need this unpleasant workaround.

Thank you!

**Comment by juliancwirko** [comment]
Nice new docs section :) thanks. I think it can be closed.
